version: '3'
#/root/mall can be change
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #
    ports:
      - 3306:3306
    volumes:
      - /root/mall/mydata/mysql/data:/var/lib/mysql #
      - /root/mall/mydata/mysql/conf:/etc/mysql/conf.d #
      - /root/mall/mydata/mysql/log:/var/log/mysql #
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /root/mall/mydata/redis/data:/data #
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.10
    container_name: nginx
    volumes:
      - /root/mall/mydata/nginx:/etc/nginx #
      - /root/mall/mydata/nginx/html:/usr/share/nginx/html #
      - /root/mall/mydata/nginx/log:/var/log/nginx #
    ports:
      - 80:80
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - /root/mall/mydata/rabbitmq/data:/var/lib/rabbitmq #
      - /root/mall/mydata/rabbitmq/log:/var/log/rabbitmq #
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #
      - "discovery.type=single-node" #
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #
    volumes:
      - /root/mall/mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #
      - /root/mall/mydata/elasticsearch/data:/usr/share/elasticsearch/data #
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.6.2
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/mall/mydata/logstash:/usr/share/logstash/pipeline #
    depends_on:
      - elasticsearch #
    links:
      - elasticsearch:es #
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    links:
      - elasticsearch:es #
    depends_on:
      - elasticsearch #
    environment:
      - "elasticsearch.hosts=http://es:9200" #
    ports:
      - 5601:5601
  mongo:
    image: mongo:4.2.5
    container_name: mongo
    volumes:
      - /root/mall/mydata/mongo/db:/data/db #
    ports:
      - 27017:27017